### ISSUE TITLE
Incorrect syntax near 'r'.

### ISSUE THREAD

**Issue by AlexanderTodorovic** [amachanic/sp_whoisactive#10]
Hi Adam, when running the script on Azure SQL Data Warehouse it runs into

```
Msg 103010, Level 16, State 1, Line 12
Parse error at line: 531, column: 36: Incorrect syntax near 'r'.
```
Is sp_whoisactive SQL Server only?

Thank you.

**Comment by amachanic** [comment]
Yes, I don't think it will work on Azure SQL Data Warehouse as it has various (major) differences in both DMVs and T-SQL support.
