### ISSUE TITLE
Empty Results Set from sp_WhoIsActive

### ISSUE THREAD

**Issue by Susja** [amachanic/sp_whoisactive#105]
Sorry Folks if this is not a right place to ask this question.
I copy/paste this stored procedure from https://github.com/amachanic/sp_whoisactive to my client.

I ran this stored procedure against my SQL server but get 'empty' Results Set. I don't have any errors.
This is the message:
Started executing query at Line 1
Warning: The join order has been enforced because a local join hint is used.
Warning: Null value is eliminated by an aggregate or other SET operation.
Total execution time: 00:00:00.228

Where should I look to check the culprit?
Thanks

**Comment by erikdarlingdata** [comment]
That’s just because no queries were running when you executed the procedure.
