### ISSUE TITLE
Result is incorrect

### ISSUE THREAD

**Issue by ibmsatya** [amachanic/sp_whoisactive#11]
The below paramenters doesn't work correct. Procedure simply retrives all rows even if no blocking.

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_NAME = 'sp_WhoIsActive')
    EXEC sp_WhoIsActive 
        @find_block_leaders = 1,
        @get_plans = 1,
        @sort_order = '[blocked_session_count] DESC'
GO

**Comment by AartBluestoke** [comment]
@find_block_leaders is like @get_plans in that it adds an extra column. It doesn't filter rows to only blockers.

**Comment by ibmsatya** [comment]
Thank you for your confirmation.

**Comment by amachanic** [comment]
Thanks for helping out here @AartBluestoke. Closing this.
