### ISSUE TITLE
XML datatype instance has too many levels of nested nodes. Maximum allowed depth is 128 levels

### ISSUE THREAD

**Issue by rwyoung01** [amachanic/sp_whoisactive#111]
I have a job that load the WhoisActive results into a table every 30 seconds.  I can not load the table when the XML SQL_TEXT has to many nested nodes.  Is there a way to filter these records or some other work around.  Load this data into a table has helped us solve some many issues.

**Comment by erikdarlingdata** [comment]
@rwyoung01 there’s no way to filter those out currently. You may need to change the column data type to nvarchar max if this is a frequent occurrence.
