### ISSUE TITLE
Is @get_transaction_info = 1 accurate?

### ISSUE THREAD

**Issue by jcggaurino** [amachanic/sp_whoisactive#112]
Hi @amachanic,
Our organization was trying to utilize this option to get transaction log information of a process/query but when testing, tran_log_writes shows mostly "0 kB" for a database that has been using most of the transaction log already. Is there an open issue with this parameter not capturing the correct data? 

![image-2023-12-20-16-16-03-656](https://github.com/amachanic/sp_whoisactive/assets/64187095/746b29ac-2262-4e0f-9c7b-762c2ca88260)
![image-2023-12-20-16-16-14-761](https://github.com/amachanic/sp_whoisactive/assets/64187095/1cd1787d-6114-4351-ace1-a98ba8b8b13f)
![image-2023-12-20-16-16-26-251](https://github.com/amachanic/sp_whoisactive/assets/64187095/1169386b-296b-4884-b467-0c1b5fc53c38)

**Comment by erikdarlingdata** [comment]
@jcggaurino yes, it is accurate. You’ve blanked out the query text so I can’t see if any modifications are executing, but when I test locally, it shows non-zero numbers where it should.

**Comment by jcggaurino** [comment]
It took a while for your update so I almost forgot this. Yup I've intentionally removed the sql text, will try to grab another occurrence of this and share here including the sql text.
