### ISSUE TITLE
SQL 2019 errors

### ISSUE THREAD

**Issue by dca00** [amachanic/sp_whoisactive#114]
sp_whoisactive used to run fine on previous versions but on SQL 2019 I get the following errors.
It was compiled by ```sa``` and runs also under ```sa``` account. I added ```with execute as owner``` as well.

```
Msg 15562, Level 16, State 2, Line 42
The module being executed is not trusted. Either the owner of the database of the module needs to be granted authenticate permission, or the module needs to be digitally signed.
Msg 15562, Level 16, State 2, Line 335
The module being executed is not trusted. Either the owner of the database of the module needs to be granted authenticate permission, or the module needs to be digitally signed.
```

What is required to run it without hiccups?

**Comment by mfuller333** [comment]
Sounds like the database you created the stored procedure in is not set to trustworthy.
