### ISSUE TITLE
Intermittent error

### ISSUE THREAD

**Issue by AndersonSouzaDBA** [amachanic/sp_whoisactive#117]
Some executions occur the attached error. Of the 3 servers, only one displays the message.
Any ideas to solve?

Environment:
SO: Windows Server 2019:
SQL Server: SQL Server 2022-CU10 Enterprise
Collation Server: SQL_Latin1_General_CP1_CI_AS

Two other environments:
SO: Windows Server 2019:
SQL Server: SQL Server 2019-CU15 Enterprise
Collation Server: SQL_Latin1_General_CP1_CI_AS

Both using the version sp_whoisactive 11.35

![ErrorSPWhoIsActive](https://github.com/amachanic/sp_whoisactive/assets/165834914/8dd1965c-ce0e-40ab-a926-8d8c3aa004ce)

**Comment by erikdarlingdata** [comment]
@AndersonSouzaDBA the current version of WhoIsActive is 12, where this has been fixed as part of #52
