### ISSUE TITLE
Has this repo become Archived/in Maintenance mode?

### ISSUE THREAD

**Issue by PureKrome** [amachanic/sp_whoisactive#118]
👋🏻 G'Day all,

just checking if this repo is in archive/maintenance mode? Not hating or trolling at all - I _totally_ get how hard and time consuming it is to maintain an OSS project. 

Just after some clarity.

🍰

**Comment by erikdarlingdata** [comment]
Yes

**Comment by erikdarlingdata** [comment]
No, it’s still active. Just slow rolling.
