### ISSUE TITLE
Sql Server 2022 Support? 

### ISSUE THREAD

**Issue by carehart** [amachanic/sp_whoisactive#120]
Folks, is sql 2022 yet formally supported? 

I was pointing someone to here in recommending the tool, when I noticed the readme.md lists 2019 as the latest supported version. If it's just a oversight, this is a heads up; I didn't want to presume to offer a PR proposing that text change, simply because it might initially "run on 2022". :-)

If there's some test suite to be run, that's great. I didn't dig that far. 

Again, I just put this question out for consideration by responsible folks here. 

(I'd argue it could also help if the front page at https://whoisactive.com/ was updated also, as it still lists only 2017 as the latest version. Only if one goes to its downloads page does that point here, which produced the question above. I do realize the two sites are separate entities, and this may not be the "right place" to raise this related suggestion.)

**Comment by erikdarlingdata** [comment]
@carehart yep, SQL Server 2022 is supported. There just hasn’t been a full release done in a bit to update the details.

**Comment by carehart** [comment]
So wait, in just closing this, that doesn't help people using 22 to know what you've asserted. :-) 

Should at least SOME verbiage about 22 be added to the Readme? If it's coming, I just didn't see it now, nor did I want to presume you intended to.

The average person is not going to search the issues to find this closed discussion. :-) As always, just trying to help.

**Comment by erikdarlingdata** [comment]
@carehart it'll be included in the next release. thanks.

**Comment by carehart** [comment]
> @carehart it'll be included in the next release. thanks.

OK, but Erik, we plebians won't know when that will be, whether days, weeks, or months from now. :-)

Again, can't you throw us/them a bone and add a sentence to that effect on the readme? And beyond that, might you (or anyone who knows) add a phrase about whether before then some of it does work for now? 

I appreciate that running an OS project is hard work, with many clamoring for their pet issues. This just seems to be a pretty key one worth pressing, here in mid-2024. The cost/benefit ratio seems vastly in favor of making a quick change while it's gotten attention. :-) 

Or if there may be something you know that totally overrides that (like the release is indeed hours or days away), I'll let it be.

**Comment by erikdarlingdata** [comment]
@carehart i've updated the readme.

**Comment by carehart** [comment]
Sweet! And sorry to be a dripping faucet for those few minutes...but thanks for turning my handle, you man, you. :-)
