### ISSUE TITLE
Sp_whoisactive

### ISSUE THREAD

**Issue by azhar74786** [amachanic/sp_whoisactive#124]
After running that procedure i am getting blank output please someone guide in messages below message is coming

Warning: The join order has been enforced because a local join hint is used.
Warning: Null value is eliminated by an aggregate or other SET operation.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/ffc48380-e5e8-4794-8a08-b67fd0f7f065">

**Comment by erikdarlingdata** [comment]
@azhar74786 that means no one is active. The warnings in the messages tab [can be ignored](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-ansi-warnings-transact-sql?view=sql-server-ver16).

**Comment by erikdarlingdata** [comment]
@azhar74786 sp_who2 is showing you background and system tasks, which sp_WhoIsActive does not show by default. You can use `@show_system_spids = 1` if you want to see those.
