### ISSUE TITLE
sys.dm_exec_requests not supported in Azure Synapse

### ISSUE THREAD

**Issue by lotsahelp** [amachanic/sp_whoisactive#13]
Running the creation script on the new Azure Synapse (aka Data Warehouse) gets 
`Msg 103010, Level 16, State 1, Line 12
Parse error at line: 528, column: 36: Incorrect syntax near 'r'.`

Running
`SELECT * FROM sys.dm_exec_requests`
gets
`Msg 104385, Level 16, State 1, Line 1
Catalog view 'dm_exec_requests' is not supported in this version.`

@@version = Microsoft Azure SQL Data Warehouse - 10.0.10665.0 Oct 6 2019 00:45:12 Copyright (c) Microsoft Corporation

**Comment by amachanic** [comment]
Yes, it's not supported there.
