### ISSUE TITLE
Error while executing .sql file , Azure 

### ISSUE THREAD

**Issue by forecaster3434** [amachanic/sp_whoisactive#16]
Iv downloaded the latest, and the previous version. Both are giving the same error:

Msg 9455, Level 16, State 1, Procedure ddl_objects_log, Line 31 [Batch Start Line 14]
XML parsing: line 5152, character 32, illegal qualified name character

database:
--SELECT @@VERSION as Ver
Ver
Microsoft SQL Azure (RTM) - 12.0.2000.8   Oct 12 2019 22:46:48   Copyright (C) 2019 Microsoft Corporation 

--SELECT SERVERPROPERTY('EngineEdition') as 'Azure_EngineEdition'
Azure_EngineEdition
5

**Comment by amachanic** [comment]
I'm not sure what ddl_objects_log is. This error has nothing to do with sp_whoisactive. Check your database for DDL triggers.
