### ISSUE TITLE
"percent_complete" does not work when @format_output is 2

### ISSUE THREAD

**Issue by amon09** [amachanic/sp_whoisactive#19]
Hey Adam - It looks like we have a typo on line 5130. It says `blocked_session_count` instead of `percent_complete`?

https://github.com/amachanic/sp_whoisactive/blob/f2ef875f77c91f0fd451c406bd0664dd55ac1322/who_is_active.sql#L5130

Thanks.

**Comment by codykonior** [comment]
(This is a note for myself, the fix for this does not fix the missing percent_complete on restores).

**Comment by amachanic** [comment]
Great catch! Please give me a PR for this. Thanks.
