### ISSUE TITLE
Please offer original_login_name

### ISSUE THREAD

**Issue by TheConstructor** [amachanic/sp_whoisactive#21]
While not available through `sys.sysprocesses`, `original_login_name` is a very handy column e.g. in `sys.dm_exec_sessions` (or `sys.dm_pdw_nodes_exec_sessions` in warehouse). We use application roles frequently and some legacy code uses `EXECUTE AS` with dynamic SQL. Especially in the later case `original_login_name` offers invaluable information.

**Comment by TheConstructor** [comment]
Have you been referring to this [ORIGINAL_LOGIN()](https://docs.microsoft.com/en-us/sql/t-sql/functions/original-login-transact-sql?view=sql-server-ver15)? It's a great function, but can only return the information from the currently executing context, and doesn't offer any parameters I am aware off.

I can try to come up with something, though I am certainly not programming a lot off the clock right now, so it may take some time. What would be hard requirements for a PR? Compatible with 2005+? Anything else?

**Comment by amachanic** [comment]
This is all set - I added it to the additional_info collection.

**Comment by TheConstructor** [comment]
@amachanic Thank You!
