### ISSUE TITLE
Strange values for Reads and CPU for fast requests

### ISSUE THREAD

**Issue by rrg92** [amachanic/sp_whoisactive#22]
Hey Guys!

Look at this case using sp__whoisactive v11.34 (happens v11.00 also) 

![image](https://user-images.githubusercontent.com/16887793/86310564-c6cd9e80-bbf4-11ea-978e-9399707d6782.png)

I guess the numbers showing in reads and CPU are very high... This environment is not able to read 200+ millions of pages in 180ms...  1.5TB in less than 1 second...

This seems a problem in whoisactive when multiple requests run in the same session very fast (complete in some milliseconds).

The environment is a Hyper-V with Windows Server 2019

**Comment by amachanic** [comment]
This just means that your I/O system is very well tuned!

Seriously, though, can you comment out line 2907, which should be:

`AND s.last_request_end_time <= sp.last_request_end_time`

... and let me know if that helps? This line seems to be causing some similar issues and I have a hunch it's related to this.

**Comment by amachanic** [comment]
@rrg92 Been a while. What did you end up doing here? Can you still reproduce this today? If so can you try the test I mentioned above? Either way, please advise on the current status.

**Comment by rrg92** [comment]
Hi Adam, sorry for the delay and thank your answer. I can't reproduce this again. We can close this issue and I will try to reproduce the issue in the future. If I see the problem I will try the fix you mentioned and reopen it. Ok for you?
