### ISSUE TITLE
Might trim query text sometimes

### ISSUE THREAD

**Issue by F8ER** [amachanic/sp_whoisactive#23]
Dear Developer,

Thank you for this project.

Although, the procedure might return trimmed query text sometimes.
Please, check [StackOverflow post](https://stackoverflow.com/a/62962519/5113030) for more information.

Regards

**Comment by BrentOzar** [comment]
That's not a bug - that's by design. If you run it while the WAITFOR is executing, then the WAITFOR is the part that's active, so that's the query that'll return. That's why Adam's proc is called sp_WhoIsActive, not sp_WhoWillBeActiveLater. It shows the currently executing statement.

**Comment by BrentOzar** [comment]
Another way to see it is to run sp_WhoIsActive several times in another window while you execute this:

```
WAITFOR DELAY '00:00:01';
SELECT GETDATE();
WAITFOR DELAY '00:00:02';
SELECT GETDATE();
WAITFOR DELAY '00:00:03';
SELECT GETDATE();
WAITFOR DELAY '00:00:04';
SELECT GETDATE();
WAITFOR DELAY '00:00:05';
SELECT GETDATE();
```

You'll notice sp_WhoIsActive isn't trimming. It's just always cleverly showing you - wait for it - who is active. ;-)

**Comment by F8ER** [comment]
Sure thing. No one said it's a bug, but someone might need a full text of query instead of a trimmed(active part of it) one.
Thus, what about adding a parameter to show such?

**Comment by BrentOzar** [comment]
You mean like @get_outer_command that’s clearly described in the documentation? http://whoisactive.com/docs/10_commands/

---
Tiny glass keyboard
Typos flowing like rivers
As winter snow thaws

**Comment by F8ER** [comment]
Sorry. Did not notice at the very end.
