### ISSUE TITLE
@sort_order doesn't seem to work

### ISSUE THREAD

**Issue by erikdarlingdata** [amachanic/sp_whoisactive#26]
While working on some Great Posts™, I found a bit of odd behavior:
![image](https://user-images.githubusercontent.com/2136037/94999275-5c772200-0586-11eb-9946-c5e8bc03604f.png)

It appears to be a case sensitivity issue, because this works:
`EXEC sp_WhoIsActive @find_block_leaders = 1, @sort_order = '[blocked_session_count] desc', @show_own_spid = 1;`

![image](https://user-images.githubusercontent.com/2136037/94999440-7107ea00-0587-11eb-9bac-63e6c043ec60.png)

Easily fixed by doing this:
```
WHEN LOWER(tokens.next_chunk) LIKE '%asc%' THEN ' ASC'
WHEN LOWER(tokens.next_chunk) LIKE '%desc%' THEN ' DESC'
```
PR incoming!

**Comment by amachanic** [comment]
Well that's what you get, I guess, for running on a case-sensitive database?!?!

Thanks for the PR! I'll push it through in a day or so.

**Comment by erikdarlingdata** [comment]
it's hard to believe that this has never come up before 😃
