### ISSUE TITLE
Rename file to dbo.sp_WhoIsActive.sql

### ISSUE THREAD

**Issue by ktaranov** [amachanic/sp_whoisactive#4]
Hi, Adam. Great thanks to move in open source club your awesome stored procedure. Could you rename `who_is_active.sql` to `dbo.sp_WhoIsActive.sql` (prefered for me ) or just `sp_WhoIsActive.sql` ?

**Comment by amachanic** [comment]
Can you share the reasoning behind that change?

**Comment by ktaranov** [comment]
Hi, Adam, thanks for quick response. It is more clear and consistent naming files with production stored procedures with schema name (we use schemas for maintaining security roles ) and procedure name. First what I do with new version of your procedure - rename the file name. Also we use case sensitive instances and for us is very important to have correct notation: `sp_whoisactive` and `sp_WhoIsActive` critical difference in this case.

**Comment by paulholmes-london** [comment]
{SchemaName}.{ObjectName}.sql is also what Redgate source control uses, capitalised exactly as the object and schema are named.

**Comment by amachanic** [comment]
Okay. This seems like a reasonable request. I'm going to pin it for a few weeks.

**If you're reading this an interested, please reply and cast a vote:**

#1 Leave it as-is
#2 sp_WhoIsActive.sql
#3 dbo.sp_WhoIsActive.sql

My vote is #2.

This is entirely due to my personal preference of organizing objects by schema in subfolders. So I'd have a subfolder called "dbo" in my project, with all of my dbo. stuff in it.

**Comment by paschott** [comment]
Torn on this. I usually name my files just as files and they sit in a separate folder for schema so no schema prefix.  I lean slightly towards #2, but wouldn't be bothered by #3.  I do agree that the name of the file matching the name of the proc is a good thing.

**Comment by ktaranov** [comment]
#3

**Comment by luporpi** [comment]
#2

**Comment by ClaudioESSilva** [comment]
# 2

**Comment by Zhunya** [comment]
2

**Comment by wdcadmin** [comment]
2

**Comment by paulholmes-london** [comment]
#3 (neither SSMS File Per Object scripting, or Redgate source control, uses folder per schema)

**Comment by BobPusateri** [comment]
2

**Comment by BruceSpruce** [comment]
2

**Comment by blaw-fc** [comment]
I prefer 3, but 2 is also fine.

**Comment by tgspacelabs** [comment]
#2

**Comment by LowlyDBA** [comment]
2

**Comment by beargle** [comment]
My preference is _3_ first, _2_ at a close second.

Some examples, for those that may not be familiar with Red Gate or the _default_ Visual Studio database project folder structures.

## Red Gate SQL Source Control (i.e. number _3_)

> ├───Assemblies
> ├───Data
> ...
> ├───Security
> ...
> │   ├───Roles
> │   ├───Schemas
> │   ├───Symmetric Keys
> │   └───Users
> ...
> ├───Stored Procedures
> │       _dbo.sp_WhoIsActive.sql_
> ├───Synonyms
> ├───Tables
> ├───Views

## Default (w/ schema folders) Visual Studio database project (i.e. number _2_)

> │   Database6.sqlproj
> ├───bin
> │   └───Debug
> ├───dbo
> │   ├───Stored Procedures
> │   │       _sp_WhoIsActive.sql_
> │   └───Tables
> ├───obj
> │   └───Debug
> ├───Security
> ...

**Comment by MisterZeus** [comment]
2 for me, because of Visual Studio defaults.

**Comment by vemund** [comment]
3

**Comment by sqlmaas** [comment]
2 because of VS.

**Comment by andrew-bickerton** [comment]
Similar to a lot of others: 3, followed by 2 as an acceptable alternative

**Comment by MattHubble** [comment]
3

**Comment by NoDakCoder** [comment]
2 looks cleaner, and I personally sort projects and archives similarly (Server > Database > Schema > File)

**Comment by bprime** [comment]
3

**Comment by waynerossi** [comment]
2, if nothing else it matches. Don't like putting the schema in file names.

**Comment by robboek** [comment]
2

**Comment by sam-bryant** [comment]
3

**Comment by AartBluestoke** [comment]
3.
reasoning:
2, if used in scenario 3 removes information which is expected to be there.
3, if used in scenario 2 shows a redundant schema, a mild cosmetic effect (summarised above by comments "don't like")

Also in terms of 'fixing' the name, it is easier to delete a spurious dbo. in the dbo folder than it is to guess which schema should be prefixed onto a schema-less object.

Therefore, a reluctant 3, because it is the only thing that 'works' in both scenarios. (if magic could occur, 2 for the people that would like it, and 3 that would like it that way, but i don't think that magic exists)

Either 2 or 3 is better than having a slightly different name for the file than the thing it deploys.

**Comment by philcart** [comment]
Would lean towards #3 as we have things arranged by object type, similar to what's in SQL Management Studio.

Could live with #2 as well.

You could also drop that "sp_" prefix :)

**Comment by ladayaroslav** [comment]
#2

**Comment by robinwilson16** [comment]
#3 is first preference and #2 is second.
I think it is good to be as explicit as possible then if anyone wants less "explicifness" they can remove the first bit themselves.

**Comment by slimrich** [comment]
#2

**Comment by mikejwhitty** [comment]
2

**Comment by Stevoni** [comment]
#3

**Comment by Eagle3386** [comment]
#2

@amachanic: may I submit two suggestions for future votings:
1. IIRC, there's a new GitHub extension for such vote calls
2. Use emoji reactions for not only less wrongly linked issues (FYI: "#<number>" creates links to that very issue), but also doesn't clutter the issue with simple replies and, most importantly, makes the counter recognizable on first sight.

**Comment by jacobgexigo** [comment]
2

**Comment by kapsiR** [comment]
>  #2 sp_WhoIsActive.sql

Matches the [First Responder Kit's](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit) naming (btw. maybe integrate it there @BrentOzarULTD)

**Comment by fredclown** [comment]
#2

**Comment by uygary** [comment]
I personally vote for option 2.
I prefer using source control for db objects, and structuring the repo along the lines of: DatabaseName/SchemaName/ObjectName.sql

Option 3 would be preferable to option 1, but it would still not be ideal due to the flattened hierarchy it causes.

**Comment by EmanueleMeazzo** [comment]
Vote for 2

**Comment by PianoMatt** [comment]
3

**Comment by spike1234** [comment]
#2

**Comment by bruce-dunwiddie** [comment]
3

**Comment by imajaydwivedi** [comment]
#2 sp_WhoIsActive.sql

**Comment by Eagle3386** [comment]
@amachanic ~1.5 years passed, so when you're choosing the winning option since you've originally wrote about pinning it "for a few weeks"?

**Comment by WaydeBunker** [comment]
#2

**Comment by cargima** [comment]
#2

**Comment by mattcargile** [comment]
#2

**Comment by runamuk0** [comment]
I like #2 as well for organization.

**Comment by bonomo1** [comment]
# 3

**Comment by atompkins** [comment]
2

**Comment by speedy32129** [comment]
2

**Comment by amachanic** [comment]
> @amachanic ~1.5 years passed, so when you're choosing the winning option since you've originally wrote about pinning it "for a few weeks"?

I've been attempting to learn the virtue of patience. :-)

(I'll get to it very shortly, I promise.)

**Comment by speedy32129** [comment]
2

**Comment by sozezzo** [comment]
**2**

**Comment by MikeyBronowski** [comment]
2

**Comment by amachanic** [comment]
Okay, I just counted the votes, finally.

2 wins.

Here's the plan: I'm going to add a second file, copy of the first, with the new name. We'll carry it for a few versions. Then we'll drop the old file. Simple :-)

**Comment by ktaranov** [comment]
@amachanic great thanks!

> I'm going to pin it for a few weeks

We also learned what a few weeks is equal to for adam smith) 118 weeks) my longest contribution to open source.
