### ISSUE TITLE
Add implicit transaction column to output

### ISSUE THREAD

**Issue by erikdarlingdata** [amachanic/sp_whoisactive#41]
On servers using the JDBC driver and other smelly unfortunates, implicit transactions can be quite an annoying problem. I wrote code into sp_BlitzWho to identify them, and I'd love to get it in sp_WhoIsActive so I don't need to use another proc for it.

It looks something like this:

```
SELECT
    des.session_id,
    CASE 
        WHEN 
            EXISTS 
            (  
                SELECT 
                    1/0 
                FROM sys.dm_tran_active_transactions AS tat
                JOIN sys.dm_tran_session_transactions AS tst
                    ON tst.transaction_id = tat.transaction_id
                WHERE tat.name = 'implicit_transaction'
                AND des.session_id = tst.session_id 
            )  THEN 1 
        ELSE 0
    END
FROM sys.dm_exec_sessions AS des;
```

**Comment by amachanic** [comment]
Definitely. Maybe as part of the @get_transaction_info output?

**Comment by erikdarlingdata** [comment]
Sure, wherever you think it makes sense.

**Comment by amachanic** [comment]
What do **you** think makes sense, Darling?

**Comment by erikdarlingdata** [comment]
Oh, you know, I think it would make more sense under `@get_additional_info = 1`, since there's other details about blocking/transactions in there, and implicit transactions are technically an [ansi default setting](https://www.erikdarlingdata.com/sql-server/be-careful-with-set-ansi_defaults-on/)

**Comment by amachanic** [comment]
Hm, really annoying that we can't harvest that information from the sessions/requests DMVs. I'm pretty sure that as far as the proc is currently concerned, the transaction DMVs are only touched when @get_transaction_info is enabled. Maybe there's a nice way to combine the two?

**Comment by erikdarlingdata** [comment]
You mean if someone reads the documentation and uses both transaction info and additional info? 😂

**Comment by amachanic** [comment]
I would never, ever imply that someone will read the documentation.

**Comment by erikdarlingdata** [comment]
That's a relief, I thought he Postgres might be going to your head.
