### ISSUE TITLE
CheckCPUPercent/Capture WhoIsActive Data

### ISSUE THREAD

**Issue by jdgleason01** [amachanic/sp_whoisactive#74]
I installed the newest release of sp_WhoIsActive, but it broke an existing Capture WhoIsActive Data job triggered by the CheckCPUPercent Alert.

**Comment by amachanic** [comment]
I have no clue what a CheckCPUPercent Alert is. That sounds like something on your end. Can you share some more information on what, exactly, broke? Did you get an error? Invalid data? Etc?
