### ISSUE TITLE
No results when running on an AG read-only secondary

### ISSUE THREAD

**Issue by gbritton1** [amachanic/sp_whoisactive#83]
I ran sp_whoisactive on a read-only secondary replica in an availability group but no results were returned.  I double checked with sp_who2 and there are 100 rows with spids over 50.  

Is there a parameter I need to set to get results this way or something else I should look at?

using v12.00

**Comment by jared-ong** [comment]
@gbritton1 probably the spids were sleeping.  You could try running with the parameter to show the sleeping spids also.  sp_who2 returns all sessions regardless whether they are "actively" doing work or not.

sp_whoisactive @show_sleeping_spids = 1

**Comment by erikdarlingdata** [comment]
@gbritton1 gonna close this one out since you haven't added any information in a while. If you have anything else to add, comment here and I'll reopen it.
