### ISSUE TITLE
Show user_name information to 'external provider' instead of login_name

### ISSUE THREAD

**Issue by aquilavqalmeida** [amachanic/sp_whoisactive#87]
In Azure SQL databases, which are using 'identity' authentication through the Azure Portal (external provider) the login_name field displays the identity internal code, which is not direct/intuitive information

![image_login](https://user-images.githubusercontent.com/104390/171492587-ac890e82-2fc7-4cf0-8d1c-06e255f586ab.png)

**Comment by erikdarlingdata** [comment]
@aquilavqalmeida I've assigned you to this issue, since it seems like you know what to do to get it sorted out and have Azure SQL DB handy to test it on.

**Comment by erikdarlingdata** [comment]
@aquilavqalmeida haven’t heard back from you in a while on this, so I’m going to close the issue out.
